const tekme = [
    {
        home: "RD LL Grosist Slovan",
        away: "RD Urbanscape Loka",
        date: "09.09.2022 - 18:30",
        result: "24:27",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna dvorana Kodeljevo"
    },
    {
        home: "RK Svi&scaron; Ivan&ccaron;na Gorica",
        away: "RD LL Grosist Slovan",
        date: "17.09.2022 - 19:00",
        result: "23:23",
        liga: "Liga NLB",
        dvorana: "Dvorana Osnovne &scaron;ole Sti&ccaron;na"
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RD Riko Ribnica",
        date: "23.09.2022 - 19:00",
        result: "31:35",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna dvorana Kodeljevo",
    },
    {
        home: "RK Maribor Branik",
        away: "RD LL Grosist Slovan",
        date: "01.10.2022 - 19:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "Dvorana Tabor",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RK Celje Pivoletna La&scaron;ko",
        date: "09.10.2022 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    },
    {
        home: "RK Slovenj Gradec",
        away: "RD LL Grosist Slovan",
        date: "21.10.2022 - 19:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Slovenj Gradec",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "MRK Krka",
        date: "05.11.2022 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    },
    {
        home: "RK Jeruzalem Ormo&zcaron;",
        away: "RD LL Grosist Slovan",
        date: "12.11.2022 - 19:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Hardek",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RK Gorenje Velenje",
        date: "19.11.2022 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    },
    {
        home: "RD Koper",
        away: "RD LL Grosist Slovan",
        date: "26.11.2022 - 19:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "Arena Bonifika",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RK Kr&scaron;ko",
        date: "03.12.2022 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RK Dobova",
        date: "10.12.2022 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    },
    {
        home: "RK Trimo Trebnje",
        away: "RD LL Grosist Slovan",
        date: "17.12.2022 - 19:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "Dvorana O&Scaron; Trebnje",
    },
    {
        home: "RD Urbanscape Loka",
        away: "RD LL Grosist Slovan",
        date: "04.02.2023 - 18:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Poden",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RK Svi&scaron; Ivan&ccaron;na Gorica",
        date: "11.02.2023 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    },
    {
        home: "RD Riko Ribnica",
        away: "RD LL Grosist Slovan",
        date: "25.02.2023 - 19:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;RC Ribnica",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RK Maribor Branik",
        date: "04.03.2023 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    },
    {
        home: "RK Celje Pivoletna La&scaron;ko",
        away: "RD LL Grosist Slovan",
        date: "18.03.2023 - 18:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "Dvorana Zlatorog",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RK Slovenj Gradec",
        date: "25.03.2023 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    },
    {
        home: "MRK Krka",
        away: "RD LL Grosist Slovan",
        date: "01.04.2023 - 19:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Marof",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RK Jeruzalem Ormo&zcaron;",
        date: "08.04.2023 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    },
    {
        home: "RK Gorenje Velenje",
        away: "RD LL Grosist Slovan",
        date: "15.04.2023 - 18:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "Rde&ccaron;a Dvorana",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RD Koper",
        date: "22.04.2023 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    },
    {
        home: "RK Kr&scaron;ko",
        away: "RD LL Grosist Slovan",
        date: "13.05.2023 - 19:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "Dvorana &Scaron;C Kr&scaron;ko",
    },
    {
        home: "RK Dobova",
        away: "RD LL Grosist Slovan",
        date: "20.05.2023 - 19:00",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Dobova",
    },
    {
        home: "RD LL Grosist Slovan",
        away: "RK Trimo Trebnje",
        date: "27.05.2023 - 18:30",
        result: "00:00",
        liga: "Liga NLB",
        dvorana: "&Scaron;portna Dvorana Kodeljevo",
    }
]

const clanskaEkipa = [

]

const miniRokomet = [ 
    {
        sola: "O&Scaron; BO&Zcaron;IDARJA JAKCA",
        termin1: "1.-2. RAZRED, PETEK 13:45-14:30",
        termin2: "3.-5. RAZRED, &Ccaron;ETRTEK 15:30-16:15",
        trener: "MATIC MARI&Ccaron;I&Ccaron; +386 68 665 077 (1.-2.r), <br> DOMEN FABIANI +386 70 559 678 (3.-5.r)",
    },
    {
        sola: "O&Scaron; JO&Zcaron;ETA MO&Scaron;KRI&Ccaron;A",
        termin1: "1.-2. RAZRED, PONEDELJEK 14:40-15:25",
        termin2: "3.-5. RAZRED, SREDA 14:40-15:25",
        trener: "ARIJAN KOVA&Ccaron;EVI&Cacute; +386 31 000 031",
    },
    {
        sola: "O&Scaron; KA&Scaron;ELJ",
        termin1: "1.-2. RAZRED, PONEDELJEK 15:30-16:15",
        termin2: "3.-5. RAZRED, PONEDELJEK 16:15-17:00",
        trener: "DON FRANKOVI&Ccaron; +386 41 548 510",
    },
    {
        sola: "O&Scaron; KETTEJA IN MURNA",
        termin1: "1.-2. RAZRED, PONEDELJEK 15:30-16:15",
        termin2: "3.-5. RAZRED, &Ccaron;ETRTEK 15:30-16:15",
        trener: "DOMEN FABIANI +386 70 559 678 (1.-2.r), <br> MATIC MARI&Ccaron;I&Ccaron; +386 68 665 077 (3.-5.r)",
    },
    {
        sola: "O&Scaron; KARLA DESTOVNIKA KAJUHA",
        termin1: "1.-2. RAZRED, PONEDELJEK 14:00-14:45",
        termin2: "3.-5. RAZRED, PONEDELJEK 14:45-15:30",
        trener: "MATIC MARI&Ccaron;I&Ccaron; +386 68 665 077",
    },
    {
        sola: "O&Scaron; MARTINA KRPANA",
        termin1: "1.-2. RAZRED, TOREK 15:30-16:15",
        termin2: "3.-5. RAZRED, TOREK 16:15-17:00",
        trener: "NINA PERKOVI&Ccaron; +386 31 586 479",
    },
    {
        sola: "O&Scaron; NOVE FU&Zcaron;INE",
        termin1: "1.-2. RAZRED, TOREK 14:30-15:15",
        termin2: "3.-5. RAZRED, TOREK 15:15-16:00",
        trener: "ARIJAN KOVA&Ccaron;EVI&Cacute; +386 31 000 031",
    },
    {
        sola: "O&Scaron; POLJANE",
        termin1: "1.-2. RAZRED, &Ccaron;ETRTEK 15:20-16:05",
        termin2: "3.-5. RAZRED, &Ccaron;ETRTEK 16:05-16:55",
        trener: "DON FRANKOVI&Ccaron; +386 41 548 510",
    },
    {
        sola: "O&Scaron; SOSTRO",
        termin1: "1.-2. RAZRED, PETEK 13:15-14:00",
        termin2: "3.-5. RAZRED, PETEK 14:00-14:45",
        trener: "ANA BERZELAK +386 51 411 998",
    },
    {
        sola: "O&Scaron; VIDE PREGARC",
        termin1: "1.-2. RAZRED, TOREK 13:50-14:35",
        termin2: "3.-5. RAZRED, &Ccaron;ETRTEK 13:50-14:35",
        trener: "PETER TER&Ccaron;I&Ccaron; +386 31 367 087",
    },
    {
        sola: "O&Scaron; ZADOBROVA",
        termin1: "1.-2. RAZRED, TOREK 14:15-15:00",
        termin2: "3.-5. RAZRED, &Ccaron;ETRTEK 14:15-15:00",
        trener: "NINA PERKOVI&Ccaron; +386 31 586 479",
    },
    {
        sola: "O&Scaron; ZALOG",
        termin1: "1.-2. RAZRED, PONEDELJEK 14:00-15:00",
        termin2: "3.-5. RAZRED, PONEDELJEK 15.00-16:00",
        trener: "NINA PERKOVI&Ccaron; +386 31 586 479",
    }
]